name: PublishDockerImage

# Run whenever the publish job runs
on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        run: |
          echo ::set-output name=version::$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')
          echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Build and push
        uses: docker/bake-action@master
        env:
          TF_VERSION: "1.1.2"
          NODE_VERSION: "16"
          GO_VERSION: "1.17"
          VERSION: ${{ steps.vars.outputs.version }}
          GIT_SHA: ${{ steps.vars.outputs.sha_short }}
        with:
          targets: |
            image-all
            image-slim-all-arch
          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max